name: 'dbt_estudo'
version: '1.0'
profile: 'default'
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

vars:
  category: Seafood

models:
  dbt_estudo:
    +materialized: table
#    +schema: "{{ target.schema }}"  # Garantir que isso seja substituído pelo valor do schema
