default:
  outputs:
    prod:
      type: redshift
      host: default-workgroup.010928215067.us-east-1.redshift-serverless.amazonaws.com
      user: admin
      password: Lu122650paulo
      port: 5439
      dbname: northwind
      schema: prod  # Schema 'prod' deve ser usado
      threads: 3

    dev:
      type: redshift
      host: default-workgroup.010928215067.us-east-1.redshift-serverless.amazonaws.com
      user: admin
      password: Lu122650paulo
      port: 5439
      dbname: northwind
      schema: public
      threads: 3

  target: prod  # Define o target padrão como 'prod'